### ISSUE TITLE
Additional scripts needed

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/PETRIC#13]
- [x] create separate script SIRF_data_preparation/download_Siemens_mMR_NEMA_IQ.py to download/mMR_NEMA_IQ
  - download from zenodo (use zenodo_get)
  - copy mMR_template_span11.hs from sirf_data_path = os.path.join(examples_data_path('PET'), 'mMR')
- [x] create script `SIRF_data_preparation/create_initial_images.py` to run OSEM and kappa and save to disk(`OSEM_image.hv`, `kappa.hv`) takes as arguments 
   - a folder-name where all the data is
   - an image-name for image size (for NEMA IQ will be the mumap as in the BSREM notebook)
- [x] NEMA_EQ specific: run script to generate ROIs
- [x] create script  `SIRF_data_preparation/create_converged_image.py` to run BSREM for along time, see #16
  - [x] compute metrics: CIL callback using `TensorBoard`

Prepared data (sinograms, OSEM_image, kappa, some plots) are at https://petric.tomography.stfc.ac.uk/data/

## TODO

- [x] overall penalty weight is fixed to 1/700, might not be ok for future data-sets. Save the value somehow (e.g. simple text file), and read it from the script?, (done in #16 as optionally reading file)
- [x] Clean-up BSREM scripts https://github.com/SyneRBI/PETRIC/tree/BSREM_scripts - the 3 datasets are identical aside from the `slice_number` for the plot and the `num_subsets` (should be parameterised?), see #16 
  - [x] merge common functionailty into one file
  - [x] use new callbacks & tensorboard logging
  - [ ] drop old-style interface of Algorithm (`algo.x`, `algo.loss`)?
- [ ] End-to-end example
  + [ ] `example_BSREM.ipynb`
    + [x] `main.py` aka `main_BSREM.py` (user-configurable) #19
    + [x] `petric.py` (read-only, we overwrite any user changes)
- [ ] another example but also showing ISTA etc
  + [x] `example_ISTA.ipynb`, `main_ISTA.py`
- [x] Update wiki to give instructions on notebook, getting data, create a status page (as we’ll need to give some more updates later). saying that from today -> added here https://github.com/SyneRBI/PETRIC/wiki/Recent-Updates
  - Registration is open
  - 3 example datasets are available (without VOIs), more to come
  - Docker build is `edge` (no release yet). Manual build is `DEVEL_BUILD=ON`.
  - Final threshold on metrics TBC
- [x] Insert "Edo's link" at https://github.com/SyneRBI/PETRIC/wiki
- [x] Make this repo public
- [x] Final consistency check
- [x] Announce

**Comment by KrisThielemans** [comment]
all done with this!
